version: "3.4"

services:
  service:
    build: .
    container_name: service
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - 27100:27017
    volumes:
      - ./backup/backup
